// <auto-generated />
using System;
using Destiny2DataLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Destiny2DataLibrary.Migrations
{
    [DbContext(typeof(Destiny2DataContext))]
    [Migration("20221101144123_ShotDamage")]
    partial class AddShotDamage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchetypePerk", b =>
                {
                    b.Property<int>("ArchetypesId")
                        .HasColumnType("integer");

                    b.Property<int>("PerksId")
                        .HasColumnType("integer");

                    b.HasKey("ArchetypesId", "PerksId");

                    b.HasIndex("PerksId");

                    b.ToTable("ArchetypePerk");
                });

            modelBuilder.Entity("Destiny2DataLibrary.Models.ActivationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PerkId")
                        .HasColumnType("integer");

                    b.Property<int>("PveDamageBuffPercent")
                        .HasColumnType("integer");

                    b.Property<int>("PveRapidFirePercent")
                        .HasColumnType("integer");

                    b.Property<int>("PvpDamageBuffPercent")
                        .HasColumnType("integer");

                    b.Property<int>("PvpRapidFireBuffPercent")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerkId");

                    b.ToTable("ActivationSteps");
                });

            modelBuilder.Entity("Destiny2DataLibrary.Models.Archetype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RoundsPerMinute")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("Archetypes");
                });

            modelBuilder.Entity("Destiny2DataLibrary.Models.Perk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivationStepsAmount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdvanced")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Perks");
                });

            modelBuilder.Entity("Destiny2DataLibrary.Models.ShotDamage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchetypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("PveBulletDamage")
                        .HasColumnType("integer");

                    b.Property<int?>("PvePrecisionBulletDamage")
                        .HasColumnType("integer");

                    b.Property<int?>("PvpBulletDamage")
                        .HasColumnType("integer");

                    b.Property<int?>("PvpPrecisionBulletDamage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchetypeId");

                    b.ToTable("ShotsDamage");
                });

            modelBuilder.Entity("Destiny2DataLibrary.Models.WeaponType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WeaponTypes");
                });

            modelBuilder.Entity("ArchetypePerk", b =>
                {
                    b.HasOne("Destiny2DataLibrary.Models.Archetype", null)
                        .WithMany()
                        .HasForeignKey("ArchetypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Destiny2DataLibrary.Models.Perk", null)
                        .WithMany()
                        .HasForeignKey("PerksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Destiny2DataLibrary.Models.ActivationStep", b =>
                {
                    b.HasOne("Destiny2DataLibrary.Models.Perk", "Perk")
                        .WithMany("ActivationSteps")
                        .HasForeignKey("PerkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perk");
                });

            modelBuilder.Entity("Destiny2DataLibrary.Models.Archetype", b =>
                {
                    b.HasOne("Destiny2DataLibrary.Models.WeaponType", "WeaponType")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("Destiny2DataLibrary.Models.ShotDamage", b =>
                {
                    b.HasOne("Destiny2DataLibrary.Models.Archetype", "Archetype")
                        .WithMany()
                        .HasForeignKey("ArchetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archetype");
                });

            modelBuilder.Entity("Destiny2DataLibrary.Models.Perk", b =>
                {
                    b.Navigation("ActivationSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
